output "original_dashboard_id" {
  value       = local.archive_data.metadata.id
  description = "The original ID of the dashboard that was restored."
}

output "restored_dashboard_id" {
  value       = dynatrace_document.restored.id
  description = "The new ID generated by Dynatrace for the restored dashboard."
}

output "restored_dashboard_name" {
  value       = dynatrace_document.restored.name
  description = "The name of the restored dashboard."
}

output "status" {
  value       = "Success. Dashboard '${local.archive_data.metadata.name}' was restored from S3. New live ID is '${dynatrace_document.restored.id}'."
  description = "Execution status message."
}
